### ISSUE TITLE
TODO's for release of VSIX 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1165]
- [x] Look into Signing issue 
- [x] Enable the selected set of analyzers by default
- [x] Version check 
- [x] Sync with new Roslyn Bits ( https://github.com/dotnet/roslyn/issues/18689 need to be completed) 
- [x] Push the vsix to gallery 
- [x] A/B gold bar 
- [x] Important Bugs 
- [x] Testing 
 - [x] Functional test

**Comment by jinujoseph** [comment]
@dotnet/analyzer-ioperation @dotnet/roslyn-analysis @kuhlenh
