### ISSUE TITLE
Update Labels

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#56]
By and large we should copy the set of labels used by [dotnet/roslyn](http://github.com/dotnet/roslyn):
- [x] 0 - Backlog (#CCCCCC)
- [x] 1 - Planning (#CCCCCC)
- [x] 2 - Ready (#CCCCCC)
- [x] 3 - Working (#CCCCCC)
- [x] 4 - In Review (#CCCCCC)
- [x] Area-Infrastructure (#5319e7)
- [x] Area-MetaCompilation (#5319e7)
- [x] Blocked (#006400)
- [x] Bug (#fc2929)
- [x] Discussion (#fbca04)
- [x] Enhancement (#fc2929)
- [x] Feature Request (#fc2929)
- [x] Localization (#fc2929)
- [x] Need More Info (#fbca04)
- [x] Question (#fc2929)
- [x] Resolution-Answered (#CCCCCC)
- [x] Resolution-By Design (#CCCCCC)
- [x] Resolution-Duplicate (#CCCCCC)
- [x] Resolution-External (#CCCCCC)
- [x] Resolution-Fixed (#CCCCCC)
- [x] Resolution-Not Applicable (#CCCCCC)
- [x] Resolution-Not Reproducible (#CCCCCC)
- [x] Resolution-Won't Fix (#CCCCCC)
- [x] Test (#fc2929)
- [x] Up for Grabs (#90EE90)
- [x] Verification Not Required (#006400)
- [x] Verified (#006400)
- [x] cla-already-signed (#009800)
- [x] cla-not-required (#90EE90)
- [x] cla-required (#e11d21)
- [x] cla-signed (#207de5)
- [x] Update existing issues with tags
